[2025-06-12T01:50:53.614+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dynamic_training_pipeline.train_random_forest scheduled__2024-10-05T15:00:00+00:00 [queued]>
[2025-06-12T01:50:53.636+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dynamic_training_pipeline.train_random_forest scheduled__2024-10-05T15:00:00+00:00 [queued]>
[2025-06-12T01:50:53.638+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-12T01:50:53.657+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_random_forest> on 2024-10-05 15:00:00+00:00
[2025-06-12T01:50:53.685+0000] {standard_task_runner.py:60} INFO - Started process 1488 to run task
[2025-06-12T01:50:53.699+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dynamic_training_pipeline', 'train_random_forest', 'scheduled__2024-10-05T15:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/dag_dynamic.py', '--cfg-path', '/tmp/tmpeh6oxig2']
[2025-06-12T01:50:53.716+0000] {standard_task_runner.py:88} INFO - Job 70: Subtask train_random_forest
[2025-06-12T01:50:53.847+0000] {task_command.py:423} INFO - Running <TaskInstance: dynamic_training_pipeline.train_random_forest scheduled__2024-10-05T15:00:00+00:00 [running]> on host caffbd336f08
[2025-06-12T01:50:53.956+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dynamic_training_pipeline' AIRFLOW_CTX_TASK_ID='train_random_forest' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T15:00:00+00:00'
[2025-06-12T01:50:53.958+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/hiring_dynamic_functions.py", line 112, in train_model
    raise FileNotFoundError(f"train.html no encontrado en: {train_html}")
FileNotFoundError: train.html no encontrado en: /opt/***/dags/2024-10-05/splits/train.html
[2025-06-12T01:50:53.970+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dynamic_training_pipeline, task_id=train_random_forest, execution_date=20241005T150000, start_date=20250612T015053, end_date=20250612T015053
[2025-06-12T01:50:53.983+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 70 for task train_random_forest (train.html no encontrado en: /opt/***/dags/2024-10-05/splits/train.html; 1488)
[2025-06-12T01:50:54.020+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-12T01:50:54.045+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
