[2025-06-12T01:01:48.539+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dynamic_training_pipeline.branching_logic scheduled__2024-10-05T15:00:00+00:00 [queued]>
[2025-06-12T01:01:48.546+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dynamic_training_pipeline.branching_logic scheduled__2024-10-05T15:00:00+00:00 [queued]>
[2025-06-12T01:01:48.546+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-12T01:01:48.558+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): branching_logic> on 2024-10-05 15:00:00+00:00
[2025-06-12T01:01:48.568+0000] {standard_task_runner.py:60} INFO - Started process 802 to run task
[2025-06-12T01:01:48.571+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dynamic_training_pipeline', 'branching_logic', 'scheduled__2024-10-05T15:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/dag_dynamic.py', '--cfg-path', '/tmp/tmpx21azu4a']
[2025-06-12T01:01:48.579+0000] {standard_task_runner.py:88} INFO - Job 83: Subtask branching_logic
[2025-06-12T01:01:48.646+0000] {task_command.py:423} INFO - Running <TaskInstance: dynamic_training_pipeline.branching_logic scheduled__2024-10-05T15:00:00+00:00 [running]> on host 5b1df1b482e5
[2025-06-12T01:01:48.680+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dynamic_training_pipeline' AIRFLOW_CTX_TASK_ID='branching_logic' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T15:00:00+00:00'
[2025-06-12T01:01:48.681+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-06-12T01:01:48.681+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 233, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_dynamic.py", line 43, in choose_branch
    if execution_date < cutoff_date:
TypeError: can't compare offset-naive and offset-aware datetimes
[2025-06-12T01:01:48.688+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dynamic_training_pipeline, task_id=branching_logic, execution_date=20241005T150000, start_date=20250612T010148, end_date=20250612T010148
[2025-06-12T01:01:48.697+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 83 for task branching_logic (can't compare offset-naive and offset-aware datetimes; 802)
[2025-06-12T01:01:48.720+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-12T01:01:48.762+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
