[2025-06-12T00:51:02.226+0000] {processor.py:161} INFO - Started process (PID=22441) to work on /opt/airflow/dags/__pycache__/dag_dynamic.py
[2025-06-12T00:51:02.227+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/dag_dynamic.py for tasks to queue
[2025-06-12T00:51:02.227+0000] {logging_mixin.py:188} INFO - [2025-06-12T00:51:02.227+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/dag_dynamic.py
[2025-06-12T00:51:02.233+0000] {logging_mixin.py:188} INFO - [2025-06-12T00:51:02.232+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/__pycache__/dag_dynamic.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/dag_dynamic.py", line 10, in <module>
    from utils.functions import create_folders, load_and_merge, split_data, train_model, evaluate_models
ModuleNotFoundError: No module named 'utils'
[2025-06-12T00:51:02.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/dag_dynamic.py
[2025-06-12T00:51:02.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/dag_dynamic.py took 0.028 seconds
